### ISSUE TITLE
Critical error after upgrade to 4.1.7

### ISSUE THREAD

**Issue by GabrielGallagher** [TangibleInc/template-system#136]
We tried updating L&L to 4.1.7 and the site crashed. 
PHP error logs show the following error:
PHP Fatal error: Uncaught Error: Call to undefined function tangible\date() in /app/www/wp-content/plugins/tangible-loops-and-logic/vendor/tangible/template-system/language/index.php:66

**Comment by GabrielGallagher** [comment]
I tried updating again, but this time took care to update Tangible Blocks before updating L&L and that seems to have gone smoothly. 
We may want to look into implementing some safeguards for these kinds of compatibility issues to prevent people from bricking their sites by having misaligned versions of different plugins in this ecosystem.

**Comment by eliot-akira** [comment]
From the issue description, it sounds like a compatibility issue with multiple versions of the template system.

Difficult to say how this could have happened, since there's a module loader that ensures only the newest version of a module is loaded. It could be that a much older version of the template system loaded itself differently.

> Uncaught Error: Call to undefined function `tangible\date()`

Just in case, I made a change in commit [8de614a](https://github.com/TangibleInc/template-system/commit/8de614a6fe130561be5967c0df842ad8e9d7d0ee) to load the Date module as early as possible, before the framework and the rest of the template system.
