### ISSUE TITLE
Warnings appearing on the frontend of the site even tho the debug displayis false

### ISSUE THREAD

**Issue by emmasteluta** [TangibleInc/template-system#44]
Earlier today I upgraded to L&L 4.0.0 on a site and everything was fine. 
I just upgraded to another site to 4.0.1 and I've got warnings appearing on the frontend of the website? Going back to 4.0.0 did not fix the problem until I've switched back to 3.3.1

![image (14)](https://github.com/TangibleInc/template-system/assets/100288691/7d9ab8b4-17f7-4fc4-9295-1b132304c627)

![image (15)](https://github.com/TangibleInc/template-system/assets/100288691/4c3a28c6-967f-4b21-a25b-4ef5b8e78c1d)

**Comment by eliot-akira** [comment]
Hi, thanks for the issue report. I looked into it, and it seems that something outside the plugin is causing it. On the site where the error is happening, do you have an older Tangible plugin installed, maybe BeaverDash? I think it's a compatibility issue with an older plugin defining the same function.

I tried to improve the way the `tangible_logic` function is loaded, to avoid this situation. Would you mind downloading the newest Template System from the link below, and trying it on the site? (From the admin, Plugins -> Add New Plugin -> Upload.)

https://codeload.github.com/TangibleInc/template-system/zip/refs/heads/main

For testing purpose, after the plugin is activated, you can deactivate L&L to ensure this one is running. If there are no warnings, it's a success and I'll update L&L with this change.

If the issue is still there - maybe you can try deactivating BeaverDash or any other Tangible plugin, if there are any, and see if it makes a difference.

**Comment by emmasteluta** [comment]
Hi @eliot-akira! Sorry for replying late. We've tested the method you've mentioned and it worked! So I think you can go and push the changes.

Thanks for looking into this one!

**Comment by eliot-akira** [comment]
Good to know, thanks!
