### ISSUE TITLE
Editor: Improve auto-completion behavior

### ISSUE THREAD

**Issue by GabrielGallagher** [TangibleInc/template-system#50]
From the Facebook group:
"If you press a single letter, e.g. ‘h’ and it suggests ‘height’, you can press tab to auto complete.
However, if you write more letters, e.g. ‘hei’, you can’t do the auto complete. It will insert ‘hei:’ and break to a new line.
The suggestions are also a bit weird. If I type ‘width:’ and then ‘f’ it will suggest ‘fantasy’. I would expect it to suggest ‘fit-content’. Maybe it’s suggesting in alphabetical order rather than being context aware?"

**Comment by eliot-akira** [comment]
It's true, the autocomplete feature is mostly using default behavior "out of the box" from CodeMirror, so the details need improvement to suit our purposes.

> press a single letter, e.g. ‘h’ and it suggests ‘height’, you can **press tab to auto complete**. However, if you write more letters, e.g. ‘hei’, you can’t do the auto complete. It will insert ‘hei:’ and break to a new line.

I've experienced the same issue, I think it's an interplay/conflict between Emmet snippet expansion, which is triggered by `TAB`, and autocomplete selection by `ENTER`. I often get confused by this while selecting an autocomplete suggestion, I hit TAB by habit and Emmet takes over, closing the autocomplete selector.

- [ ] Solution: Disable Emmet while the autocomplete selector is open, so that the `TAB` key selects the suggestion as expected, same as `ENTER`.

---

> suggestions are also a bit weird. If I type ‘width:’ and then ‘f’ it will suggest ‘fantasy’. I would expect it to suggest ‘fit-content’. Maybe it’s suggesting in alphabetical order rather than being context aware?

This is about the default autocomplete definitions that comes with CodeMirror's HTML language extension. I've already forked it for customization, so I can:

- [ ] Look into making the suggestions more intuitive

It's true that the suggestions are currently shown simply in alphabetical order. Making it context aware is not so simple, there would need to be some "smart" logic built into the autocomplete function.

**Comment by eliot-akira** [comment]
Solved by: [Editor: Change key map to expand Emmet abbreviation to Shift+TAB, to prevent conflict with TAB to select autocomplete suggestion](https://github.com/TangibleInc/template-system/commit/56950f1cf8f6a85e5af962995b22083ca5d647c8).
