### ISSUE TITLE
Framework: Sync last changes with repository

### ISSUE THREAD

**Issue by nicolas-jaussaud** [TangibleInc/template-system#56]
Hi @eliot-akira!

I would like to sync the last changes from template-system to the framework repository, but I'm still unsure about how to proceed

Could you help me understand how to do it?

**Comment by eliot-akira** [comment]
So, I tried to update it myself first to make sure it works - and found that there's no simple way to merge new commits from the Template System to the Framework module. I think I'll need to write a script to automate it somehow.

To explain, the Framework module was created by following this article in the GitHub docs: [Splitting a subfolder out into a new repository](https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository). I also read several other articles on the same topic, and the concensus is to use a tool called [`git-filter-repo`](https://github.com/newren/git-filter-repo), which adds a new Git command.

However, after various attempts, I learned (newren/git-filter-repo#329) that the resulting repo is meant to be a one-time conversion, and it's a huge pain to reguarly merge from upstream due to merge conflicts of re/moved files.

In the end, what worked was to recreate the child repo every time, which preserves all the Git history from the parent.

```sh
git clone git@github.com:TangibleInc/template-system.git framework
cd framework
git filter-repo --subdirectory-filter framework
git remote add origin git@github.com:TangibleInc/framework.git
git push --set-upstream origin main --force
```

I could write a script within the Template System to run the above commands. But it would depend on `git-filter-repo` being installed on the local system. (This tool is written in Python.)

That's too bad, because I was hoping to split other folders from the Template System into their own repos. Apparently, there's a tool called [`josh`](https://github.com/josh-project/josh) (Just One Single History - written in Rust) that achieves this in a simpler way, but I'd like to avoid requiring an external dependency.

So I think the solution is to write a script that achives the same thing with plain Git, if possible.

**Comment by nicolas-jaussaud** [comment]
Thank you for explaining the process, and for updating the framework!

It seems github will consider that it's a completly new repository:
![image](https://github.com/TangibleInc/template-system/assets/33153717/f7592d33-83e0-4254-a670-374f7fcca9a1)

I guess it's normal if you had to delete the existing repository and create an empty new one before running the script, but my understanding is that you did a `git push --set-upstream origin main --force` on the previous repository

I don't know if it's an issue, it's just to let you know in case it's unexpected

**Comment by eliot-akira** [comment]
Ah yes, that was when I was trying different approaches, and ran into this issue:

- newren/git-filter-repo#227

In an attempt to solve it, I deleted the repo and re-created it. But that didn't solve it either. Apparently the issue is due to `git-filter-repo` rewriting Git history, and on the side of GitHub, they don't fully support this use case.

From everything I've read, there's no simple/ideal way to manage a Git repo with multiple child Git repos. There's git [submodule](https://diziet.dreamwidth.org/14666.html), [subtree](https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository), and community-created tools like [filter-repo](https://github.com/newren/git-filter-repo), [subrepo](https://github.com/ingydotnet/git-subrepo).. (Actually this last one I've looked at before, it seems close to what I want to achieve - and it's written in shell script without dependencies.)

Well, hopefully I'll settle on a good solution soon. :smiley:
