### ISSUE TITLE
Associating pagination with a target loop by unique name

### ISSUE THREAD

**Issue by eliot-akira** [TangibleInc/template-system#62]
> Support pagination before/after loops, or multiple paginations per loop, by associating each pagination with a target loop by unique name

```html
<PaginateButtons name=loop_name>
```

How to give a name to a loop? Can't use `name` because that's a query parameter already. Maybe something like `pagination_name`.
    
```html
<Loop type=post paged=5 pagination_name=loop_name>
```

**Comment by GabrielGallagher** [comment]
Does the "pagination_name" part make sense, or should we just have something more generic like "loop_id" so that if future syntax requires targeting a loop from outside it (filter facets for instance), you don't have to add another parameter? I dunno if "loop_id" implies the eventual "loop_class" for target all loops of a certain type, if ever that would come up.

**Comment by eliot-akira** [comment]
Good idea, I had a similar thought about future extensibility of giving a unique name to a loop, for purposes other than pagination. I like `loop_id`.

I think it would make sense to use the same attribute name to target it.

```html
<Loop type=post paged=5 loop_id=recent_posts>
  ...
</Loop>

<PaginateButtons loop_id=recent_posts>
```
