### ISSUE TITLE
orderby=date is not working on learndash_course Loop type

### ISSUE THREAD

**Issue by ghen-arvesu** [TangibleInc/template-system#65]
Hi @eliot-akira ,
 There seem to be a problem on the learndash course integration and the ACF post loop integration. Once we add the orderby=date order=asc then the excerpt and the other details are getting lost.

Here is how we used it. 
        
```
         <Loop type=learndash_course enrolled=true orderby=date order=asc>
            <Template name=course-item />
          </Loop>
```

Template: Course Item

```
<Loop acf_post=course_product>
  <Set course_duration><Field duration /></Set>
  <Set course_excerpt><Field excerpt /></Set>
  <Set product_id><Field id /></Set>
  <Set product_url><Field url /></Set>
</Loop>
<Set course_has_product><If variable=product_id>1</If></Set>
<Set user_has_access><If field=course_enrolled value="TRUE">1</If></Set>
<li class="tt-list__item card">
  <div class="tt-list__item__inner">
    <div class="tt-list__item__content">
      <div class="tt-list__item__title"><Field title /></div>
      <div class="tt-list__item__description"><Get course_excerpt /></div>
```

**Comment by eliot-akira** [comment]
Thank you for the issue report, the templates are helpful to see. If I understand correctly, each LearnDash course has an ACF Post field called `course_product`.

To help narrow down the cause, can you try the following simplified templates? We can see where it stops working.

- 1\. Get course product: Loop without `orderby` or separate template

  ```html
  <Loop type=learndash_course enrolled=true count=1>
    <Loop acf_post=course_product>
      Course Product: <Field id /> - Excerpt: <Field excerpt />
    </Loop>
  </Loop>
  ```

  If this doesn't work, the issue is related to the ACF Post field, how it's not able to find the associated course product.

- 2\. Get course product: Loop without separate template

  ```html
  <Loop type=learndash_course enrolled=true orderby=date order=asc count=1>
    <Loop acf_post=course_product>
      Course Product: <Field id /> - Excerpt: <Field excerpt />
    </Loop>
  </Loop>
  ```

  If this doesn't work, the issue is related to the LearnDash Course loop type and how it processes `orderby`.

- 3\. Get course product: Loop with separate template

  ```html
  <Loop type=learndash_course enrolled=true orderby=date order=asc count=1>
    <Template name=course-product-test />
  </Loop>
  ```

  Template: `course-product-test`

  ```html
  <Loop acf_post=course_product>
    Course Product: <Field id /> - Excerpt: <Field excerpt />
  </Loop>
  ```

  If this doesn't work, the issue is related to the `Template` tag and how the loaded template is not able to get the ACF Post field from the current LearnDash course.

**Comment by ghen-arvesu** [comment]
Hey @eliot-akira thanks so much for your response. 
We were able to solve this by noticing that:
1. The course is not actually associated with the product and
2. we had to reset the loop values to show the correct values

**Comment by eliot-akira** [comment]
Good to know! :smile:
