### ISSUE TITLE
Update Sass/SCSS

### ISSUE THREAD

**Issue by BenTangible** [TangibleInc/template-system#85]
Hey @eliot-akira, could you update the version of SASS in the plugin? I'm told some of the frontend folks have encountered linting issues and I know we've got a few open issues related to L&L's style tab. Might be worth updating that to see if that might address the issues people have encountered. Sorry I don't have more specifics, I've just been asked to be the messenger to ask for an update :)

**Comment by eliot-akira** [comment]
For reference, there are two parts to Sass support in the Template System.

- Sass compiler on server side using [SCSS-PHP](https://github.com/scssphp/scssphp)
- Sass linter and syntax hightlight for the code editor on the frontend ([@codemirror/lang-sass](https://github.com/codemirror/lang-sass))

As you've probably noticed, the Sass language is a moving target and SCSS-PHP implements only a subset of the specs. Maintaining compatibility has been a bit of a pain, and I'm somewhat dissatisfied with the direction the language is evolving too.

I'm wondering if we can eventually transition to using plain CSS as the default, since CSS has grown to incorporate Sass-like features such as variables and nested rules. Another angle I'm considering is to use the browser-build of the official compiler ("reference implementation") called [dart-sass](https://github.com/sass/dart-sass).

Anyway, I've upgraded both front/backend Sass support. Still didn't solve, for example, this issue:

- https://github.com/TangibleInc/template-system/issues/82#issuecomment-1986181813
